#!/usr/bin/env cwl-runner
cwlVersion: v1.2
class: Workflow
id: MC_MinBias_2025_W43_45_MagDown_nu1
label: MinBias 2025.W43.45 pp MagDown nu=1.0, no spillover (30000000)
doc: |-
  LHCb Run 3 simulation workgraph: minimum bias, 2025.W43.45 pp MagDown

  Metadata:
    Event Type: 30000000 (minimum bias)
    Sim Condition: Beam6800GeV-2025.W43.45-MagDown-Nu1.0-Pythia8
      (production uses Nu7.6-25ns; pileup reduced and spillover
      disabled here so the example runs in a few minutes)
    Simulation: Sim10h
    Based on: lhcb-simulation/mc-requests!2372 (Lb2Lmumu_run3)

  This workgraph contains 3 transformations:
    1. MCSimulation     — Gauss (transformations/transformation-1.cwl)
    2. MCReconstruction — Boole, HLT1 (transformations/transformation-2.cwl)
    3. MCMerge          — merge the HLT1 DSTs (transformations/transformation-3.cwl)

  It has no input data: events are generated by the first transformation.

$namespaces:
  dirac: https://diracgrid.org/cwl#

requirements:
  InlineJavascriptRequirement: {}
  SubworkflowFeatureRequirement: {}
  StepInputExpressionRequirement: {}
  MultipleInputFeatureRequirement: {}
  ResourceRequirement:
    coresMin: 1
    ramMin: 4096

# The dirac:* hint vocabulary will be defined by a versioned JSON schema
# that is still being designed: the field names below are illustrative,
# not final.
hints:
  # Marks this workflow as a workgraph.
  # To be expanded once ADR is finalised.
  dirac:Workgraph: {}

inputs:
  output-prefix:
    doc: 'Output file prefix (format: PPPPPPPP_JJJJJJJJ where P=production-id,
      J=prod-job-id). Gauss derives its random seeds from it.'
    default: '00012345_00006789'
    type: string
  n-of-events:
    doc: Number of events to generate
    default: 2
    type: int

steps:
  transformation_1:
    doc: Generate and simulate events with Gauss
    hints:
      # Marks this step as a transformation. In LHCbDIRAC: an
      # MCSimulation transformation, one Gauss step per job.
      # To be expanded once ADR is finalised.
      dirac:Transformation: {}
    run: transformations/transformation-1.cwl
    in:
      output-prefix: output-prefix
      n-of-events: n-of-events
    out: [SIM, others]

  transformation_2:
    doc: Digitise, then run HLT1 over the simulated events
    hints:
      # In LHCbDIRAC: an MCReconstruction transformation running several
      # application steps per job over groups of 3 SIM files.
      # To be expanded once ADR is finalised.
      dirac:Transformation: {}
    run: transformations/transformation-2.cwl
    in:
      input-data: transformation_1/SIM
      output-prefix: output-prefix
    out: [HLT1_DST, others]

  transformation_3:
    doc: Merge the HLT1 DSTs produced by transformation_2
    hints:
      # In LHCbDIRAC: an MCMerge transformation over groups of 8 files.
      # To be expanded once ADR is finalised.
      dirac:Transformation: {}
    run: transformations/transformation-3.cwl
    in:
      input-data: transformation_2/HLT1_DST
      output-prefix: output-prefix
    out: [HLT1_DST, others]

outputs:
  HLT1_DST:
    label: 'Output Data: HLT1.DST'
    outputSource: transformation_3/HLT1_DST
    type: File[]
  others:
    label: Logs and summaries
    outputSource:
    - transformation_1/others
    - transformation_2/others
    - transformation_3/others
    linkMerge: merge_flattened
    type: File[]
