[project]
authors = [{name = "natthan-pigoux", email = "natthan-pigoux@users.noreply.github.com"}]
dependencies = ["cwltool", "ctapipe==0.30.0", "eventio~=2.1", "typer"]
name = "duw_cwl_hands_on"
requires-python = ">= 3.12"
version = "0.1.0"

[project.optional-dependencies]
test = ["pytest", "pytest-cov", "pytest-requirements"]

[build-system]
requires = ["setuptools>=65", "setuptools_scm[toml]>=8"]
build-backend = "setuptools.build_meta"

[tool.pixi.workspace]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tool.pixi.pypi-dependencies]
duw_cwl_hands_on = { path = ".", editable = true }

[tool.pixi.tasks]
create-dl0-dl2-input = { cmd = "create-dl0-dl2-input", description = "Get a CTAO Simulation dataset."}
create-multi-dl1-input = { cmd = "create-multi-dl1-input", description = "Create multiple DL1 input files."}

# Pre-commit
[tool.pixi.feature.pre-commit.dependencies]
pre-commit = "*"

[tool.pixi.feature.pre-commit.tasks]
pre-commit = { cmd = "pre-commit run -a", description = "Run pre-commit"}

[tool.pixi.environments]
default = { solve-group = "default" }
pre-commit = { features = ["pre-commit"], solve-group = "default"}

## RUFF
# -----
[tool.ruff]
line-length = 88
target-version = "py312"

[tool.ruff.lint]
extend-select = [
    "I", # isort
    "N", # pep8 naming
    "D", # pydocstyle
    "NPY", # numpy
    "PT", # pytest
    "UP", # pyupgrade
    "COM", # flake8-commas
    "ISC", # implicit string concat rules
    "ICN", # import name conventions
    "G", # logging
]
ignore = [
    "COM812", # incompatible with ruff format
    "ISC001", # incompatible with ruff format
]

[tool.ruff.lint.pydocstyle]
convention = "numpy"

[tool.ruff.lint.per-file-ignores]
# no documentation linting for test files
"**/tests/**" = ["D"]
"**/tests_*.py" = ["D"]
"examples/**" = ["D"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"

[tool.repo-review]
select = ["PY", "PP", "PC"]
ignore = [
    "PY007", # we do not use tox for now
    "PC140", # mypy is not used
    "PC170", # pygrep is not used
    "PC180", # prettier is not used
    "PC111", # blacken-docs is not used
    "PC901", # no CI setup currently for updating pre-commit hooks
]

[tool.pytest.ini_options]
minversion = "7"
testpaths = ["src"]
log_cli_level = "INFO"
log_cli_format = "%(asctime)s %(levelname)s %(name)s %(message)s"
log_date_format = "%Y-%m-%d %H:%M:%S.%f"
xfail_strict = true
addopts = ["-ra", "--strict-config", "--strict-markers", "-p", "pytest_requirements"]

filterwarnings = [
    "error",
]

[project.scripts]
create-dl0-dl2-input = "duw_cwl_hands_on.cli.create_dl0_dl2_input:app"
create-multi-dl1-input = "duw_cwl_hands_on.cli.create_multiple_dl1_inputs:app"
